version: "3"

services:
  superagent-api:
    container_name: superagent-api
    network_mode: ${NETWORK_MODE}
    build:
      context: ..
      dockerfile: Dockerfile
    command: ["/bin/bash", "setup.docker.sh"]
    environment:
      - PORT=8080
    ports:
      - 8080:8080
    env_file:
      - ../.env
    depends_on:
      pgdb:
        condition: service_healthy
      pgadmin:
        condition: service_started
    restart: unless-stopped

  pgdb:
    container_name: pgdb
    network_mode: ${NETWORK_MODE}
    image: postgres:12
    restart: unless-stopped
    volumes:
      - type: volume
        source: pgdb-data
        target: "/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASS}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DBUSER}"]
      interval: 30s
      timeout: 30s
      retries: 3

  pgadmin:
    container_name: pgadmin
    network_mode: ${NETWORK_MODE}
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_LISTEN_PORT: 5050
    volumes:
      - type: volume
        source: pgadmin-data
        target: /root/.pgadmin
    restart: unless-stopped

volumes:
  pgdb-data:
  pgadmin-data:
